### ISSUE TITLE
Exception in thread "main" javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by xia-rongyan** [ocopea/cloudfoundry#14]
I installed everything with the help of TirumalaiAnandanpillaiPursai, Vijay, and the last step of install the script it reported below errors:

root@xias1ububtu:~/cloudfoundry-master/deployer/target/classes# cf cups postgres -p "url,username,password"
url> postgresql://10.62.90.227:5432/postgres
username> postgres
password> postgres
Creating user provided service postgres in org loris / space pr-2183 as loris...
OK

And then I rerun the deploy.sh

Everything goes well until at the end: 

     state     since                  cpu    memory         disk           details
#0   running   2018-03-27T03:18:28Z   1.3%   129M of 512M   165.1M of 1G
     state     since                  cpu    memory         disk           details
#0   running   2018-03-27T03:18:29Z   1.3%   132M of 512M   157.4M of 1G
configuration url: http://root-configuration.10.62.90.144.nip.io/configuration-api
Exception in thread "main" javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:209)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
        at com.sun.proxy.$Proxy31.registerPsb(Unknown Source)
        at com.emc.ocopea.demo.cftriple.ApiInvoker.addPsb(ApiInvoker.java:113)
        at com.emc.ocopea.demo.cftriple.OcopeaClient.bindOcopea(OcopeaClient.java:659)
        at com.emc.ocopea.demo.cftriple.OcopeaClient.main(OcopeaClient.java:86)
Deleting app root-configurator in org loris / space pr-2183 as loris...
OK
http://root-orcs.10.62.90.144.nip.io/hub-web-api/html/nui/index.html

I am able to access the above url, but nothing can be added(even though inside this space it has several other applications running). Is there anything I miss ?

**Comment by vjtirumalai** [comment]
The issue is that we hard code the PCF credentials when building Ocopea. This is required as Ocopea needs to talk to your PCF space to be able to deploy data services.

**Workaround**: For now please change the credentials in cf-tools/client/src/main/java/com/emc/ocopea/demo/cftriple/OcopeaClient.java::registerCFPaaSServiceDependencies method when creating instance of CloudFoundryClientResourceConfiguration.

We will have to figure out a better way to set these.
I will update the docs.
